apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app-2
spec:
  rules:
    - host: "python-app-2.test.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-app-2
                port:
                  number: 8080
